name: food_desk
description: "FoodDesk - Meal ordering app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.3

flutter:
  uses-material-design: true
  assets:
    - assets/ProductImages/
    - assets/app_logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app_logo.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/app_logo.png"
  android: true
  ios: true